BEGIN TRANSACTION;

-- Capacidade
CREATE TABLE IF NOT EXISTS DimCapacidade(
    id INT GENERATED ALWAYS AS IDENTITY,
    quantidade INT NOT NULL DEFAULT(100),

    CONSTRAINT id_capacidade_pk PRIMARY KEY(id)
);

--EBO
CREATE TABLE IF NOT EXISTS DimEbo(
    id INT GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    is_ativo BOOLEAN DEFAULT(TRUE) NOT NULL,

    CONSTRAINT id_ebo_pk PRIMARY KEY(id)
)

-- Faq
CREATE TABLE IF NOT EXISTS DimFaq(
    id INT GENERATED ALWAYS AS IDENTITY,
    pergunta VARCHAR(100) NOT NULL,
    resposta TEXT NOT NULL,
    ordem INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_ativo BOOLEAN DEFAULT(TRUE) NOT NULL,
    data_criacao TIMESTAMPTZ DEFAULT(now()) NOT NULL,

    CONSTRAINT id_faq_pk PRIMARY KEY(id)
);

-- Ingressos
CREATE TABLE IF NOT EXISTS DimIngresso(
    id INT GENERATED ALWAYS AS IDENTITY,
    nome_tipo VARCHAR(100) UNIQUE NOT NULL,
    descricao VARCHAR(200) NOT NULL,
    observacao TEXT,
    quantidade_pessoas INT NOT NULL DEFAULT(1),
    ordem INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    preco DECIMAL(10,2) NOT NULL,
    data_fim_vendas TIMESTAMPTZ,
    is_ativo BOOLEAN DEFAULT(TRUE),

    CONSTRAINT id_ingresso_pk PRIMARY KEY(id)
);

-- Cargo
CREATE TABLE IF NOT EXISTS DimCargo(
    id INT GENERATED ALWAYS AS IDENTITY, 
    nome VARCHAR(100) UNIQUE NOT NULL,
    is_ativo BOOLEAN DEFAULT(TRUE) NOT NULL,

    CONSTRAINT id_cargo_pk PRIMARY KEY(id)
);

-- Congregação
CREATE TABLE IF NOT EXISTS DimCongregacao(
    id INT GENERATED ALWAYS AS IDENTITY, 
    nome VARCHAR(100) UNIQUE NOT NULL,
    is_ativo BOOLEAN DEFAULT(TRUE) NOT NULL,

    CONSTRAINT id_congregacao_pk PRIMARY KEY(id)
);

-- Comprador
CREATE TABLE IF NOT EXISTS DimComprador(
    cpf_cnpj VARCHAR(100) UNIQUE NOT NULL,
    nome VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    whatsapp VARCHAR(100),

    CONSTRAINT cpf_cnpj_comprador_pk PRIMARY KEY(cpf_cnpj)
);

-- Usuário
CREATE TYPE enum_nivel AS ENUM('super_admin', 'financeiro', 'portaria');
CREATE TABLE IF NOT EXISTS DimUsuario(
    id UUID DEFAULT (gen_random_uuid()) NOT NULL,
    nome VARCHAR(250) NOT NULL,
    email VARCHAR(250) UNIQUE NOT NULL,
    nivel enum_nivel DEFAULT('super_admin') NOT NULL,
    is_ativo BOOLEAN DEFAULT(TRUE) NOT NULL,

    CONSTRAINT id_usuario_pk PRIMARY KEY(id)
);

-- Transação
CREATE TYPE enum_status_pagamento AS ENUM('pendente', 'aprovado', 'cancelado');
CREATE TYPE enum_metodo_pagamento AS ENUM('cartao', 'boleto', 'pix', 'dinheiro');
CREATE TABLE IF NOT EXISTS FactTransacao(
    id UUID DEFAULT(gen_random_uuid()) NOT NULL,
    id_comprador VARCHAR(100) NOT NULL,
    id_ingresso INT NOT NULL,
    id_pagamento_mp VARCHAR(200),
    id_ebo INT NOT NULL,
    status_pagamento enum_status_pagamento NOT NULL DEFAULT('pendente'),
    metodo_pagamento enum_metodo_pagamento NOT NULL,
    valor_pedido DECIMAL(10,2) NOT NULL,
    data_hora_pedido TIMESTAMPTZ DEFAULT(now()) NOT NULL,

    CONSTRAINT id_transacao_pk PRIMARY KEY(id),
    CONSTRAINT id_comprador_transacao_fk FOREIGN KEY(id_comprador) REFERENCES DimComprador(cpf_cnpj),
    CONSTRAINT id_ingresso_transacao_fk FOREIGN KEY(id_ingresso) REFERENCES DimIngresso(id),
    CONSTRAINT id_ebo_transacao_fk FOREIGN KEY(id_ebo) REFERENCES DimEbo(id)
);
CREATE INDEX idx_transacao_id_comprador ON FactTransacao(id_comprador);
CREATE INDEX idx_transacao_id_ingresso ON FactTransacao(id_ingresso);
CREATE INDEX idx_transacao_id_ebo ON FactTransacao(id_ebo);

-- Credencial
CREATE TABLE IF NOT EXISTS DimCredencial(
    id INT GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR(200) NOT NULL,
    id_transacao UUID NOT NULL,
    id_cargo INT NOT NULL,
    id_congregacao INT,
    is_outra_congregacao BOOLEAN NOT NULL DEFAULT(FALSE),
    nome_outra_congregacao VARCHAR(200),
    is_titular BOOLEAN DEFAULT(TRUE) NOT NULL,

    CONSTRAINT id_credencial_pk PRIMARY KEY(id),
    CONSTRAINT id_transacao_credencial_fk FOREIGN KEY(id_transacao) REFERENCES FactTransacao(id),
    CONSTRAINT id_congregacao_credencial_fk FOREIGN KEY(id_congregacao) REFERENCES DimCongregacao(id),
    CONSTRAINT id_cargo_credencial_fk FOREIGN KEY(id_cargo) REFERENCES DimCargo(id),
    CONSTRAINT nome_outra_congregacao_id_congregacao_credencial_ck CHECK(
        (is_outra_congregacao = FALSE AND id_congregacao IS NOT NULL AND nome_outra_congregacao IS NULL )
        OR 
        (is_outra_congregacao = TRUE AND id_congregacao IS NULL AND nome_outra_congregacao IS NOT NULL)
    )
);
CREATE INDEX idx_credencial_nome ON DimCredencial(nome);
CREATE INDEX idx_credencial_id_transacao ON DimCredencial(id_transacao);
CREATE INDEX idx_credencial_id_cargo ON DimCredencial(id_cargo);
CREATE INDEX idx_credencial_id_congregacao ON DimCredencial(id_congregacao);

-- Checkin
CREATE TABLE IF NOT EXISTS FactCheckin(
    id INT GENERATED ALWAYS AS IDENTITY,
    id_credencial INT NOT NULL,
    data_hora_checkin TIMESTAMPTZ DEFAULT(now()) NOT NULL,
    id_usuario UUID NOT NULL,

    CONSTRAINT id_checkin_fk PRIMARY KEY(id),
    CONSTRAINT id_credencial_checkin_fk FOREIGN KEY(id_credencial) REFERENCES DimCredencial(id),
    CONSTRAINT id_usuario_checkin_fk FOREIGN KEY(id_usuario) REFERENCES DimUsuario(id)
);
CREATE INDEX idx_checkin_id_credencial ON FactCheckin(id_credencial);
CREATE INDEX idx_checkin_id_usuario ON FactCheckin(id_usuario);

COMMIT;