import type { Metadata } from "next";
import { Montserrat, Cormorant_Garamond } from "next/font/google";
import "./main.scss";
import AuthContext from "@/contexts/AuthContexts";
import DataContext from "@/contexts/DataContext";

const cormorant = Cormorant_Garamond({
    subsets: ["latin"],
    variable: "--font-serif",
});
const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="pt-BR"
            className={`${montserrat.variable} ${cormorant.variable}`}
            data-scroll-behavior="smooth" // Isso diz que aplicamos o scroll smooth na página para evitar saltos indesejados
        >
            <AuthContext>
                <DataContext>
                    <body>{children}</body>
                </DataContext>
            </AuthContext>
        </html>
    );
}
