export const testeIngressos: IngressosInterface[] = [
    {
        id: 0,
        nome_tipo: "individual",
        descricao: "Acesso único completo a todos os dias da EBO",
        observacao: "Filhos não pagam entrada",
        preco: 60,
        quantidade_pessoas: 1,
        ordem: 2,
        is_ativo: true,
        data_fim_vendas: "2026-06-01T14:30:00Z",
    },
    {
        id: 1,
        nome_tipo: "casal",
        descricao: "Acesso completo para o casal a todos os dias da EBO",
        observacao: "Filhos não pagam entrada",
        preco: 100,
        quantidade_pessoas: 2,
        ordem: 1,
        is_ativo: true,
        data_fim_vendas: "2026-06-05T14:30:00Z",
    },
];

const congregacoes = [
    { nome: "kemel", is_ativo: true },
    { nome: "sede", is_ativo: true },
    { nome: "amanda i", is_ativo: true },
    { nome: "brasilândia", is_ativo: true },
    { nome: "capadócia", is_ativo: true },
    { nome: "colégio", is_ativo: true },
    { nome: "comunitário", is_ativo: true },
    { nome: "pq. fernanda", is_ativo: true },
    { nome: "eduardo", is_ativo: true },
    { nome: "eledy", is_ativo: true },
    { nome: "fátima", is_ativo: true },
    { nome: "fughiara", is_ativo: true },
    { nome: "ipê", is_ativo: true },
    { nome: "japão", is_ativo: true },
    { nome: "macedônia", is_ativo: true },
    { nome: "marabá", is_ativo: true },
    { nome: "mimas", is_ativo: true },
    { nome: "miraí", is_ativo: true },
    { nome: "nova europa", is_ativo: true },
    { nome: "rincão", is_ativo: true },
    { nome: "são francisco", is_ativo: true },
    { nome: "sete lagoas", is_ativo: true },
    { nome: "tereza", is_ativo: true },
    { nome: "trianon", is_ativo: true },
    { nome: "valo verde", is_ativo: true },
    { nome: "valquíria", is_ativo: true },
    { nome: "varginha", is_ativo: true },
    { nome: "mg araxá", is_ativo: true },
    { nome: "mg araxá urciano lemos", is_ativo: true },
    { nome: "mg divinópolis", is_ativo: true },
    { nome: "mg dores de indaiá", is_ativo: true },
    { nome: "mg estrela do indaiá", is_ativo: true },
    { nome: "mg ibiá", is_ativo: true },
    { nome: "mg lagoa da prata", is_ativo: true },
    { nome: "mg quartel geral", is_ativo: true },
    { nome: "mg rio pomba", is_ativo: true },
    { nome: "vila real", is_ativo: true },
];
export const testeCongregacoes: CongregacaoInterface[] = congregacoes.map(
    (v, i) => ({ ...v, id: i }),
);

const cargos = [
    { nome: "obreiro", is_ativo: true },
    { nome: "diácono", is_ativo: true },
    { nome: "pastor", is_ativo: true },
    { nome: "cooperador", is_ativo: true },
    { nome: "membro", is_ativo: true },
    { nome: "outro", is_ativo: true },
];
export const testeCargos: CargosInterface[] = cargos.map((v, i) => ({
    id: i,
    ...v,
}));

const perguntas = [
    {
        data_criacao: "2026-06-01T14:30:00Z",
        ordem: 1,
        is_ativo: true,
        pergunta: "O ingresso é válido para todos os dias do evento?",
        resposta:
            "Sim! Ao adquirir o seu ingresso, você garante acesso completo aos 4 dias da 19ª EBO.",
    },
    {
        data_criacao: "2025-06-01T14:30:00Z",
        ordem: 2,
        is_ativo: true,
        pergunta: "Preciso comprar ingresso para os meus filhos?",
        resposta:
            "Não! É uma alegria para nós receber a sua família. Filhos não pagam entrada e têm acesso gratuito aos dias de evento acompanhados dos pais.",
    },
    {
        data_criacao: null,
        ordem: 3,
        is_ativo: true,
        pergunta: "Haverá estacionamento no local?",
        resposta:
            "Sim, contamos com estacionamento gratuito no local, sujeito à lotação. Recomendamos chegar com pelo menos 30 minutos de antecedência para garantir sua vaga com tranquilidade.",
    },
];
export const testePerguntas: FAQInterface[] = perguntas
    .map((v, i) => ({
        ...v,
        id: i,
    }))
    .sort((a, b) => a.ordem - b.ordem);

export const testeCompradores: CompradorInterface[] = [
    {
        cpf_cnpj: "11111111111",
        nome: "João Silva",
        email: "joao.silva@email.com",
        whatsapp: "16999990001",
    },
    {
        cpf_cnpj: "22222222222",
        nome: "Maria Oliveira",
        email: "maria.oliveira@email.com",
        whatsapp: "16999990002",
    },
    {
        cpf_cnpj: "33333333333",
        nome: "Pedro Santos",
        email: "pedro.santos@email.com",
        whatsapp: "16999990003",
    },
    {
        cpf_cnpj: "44444444444",
        nome: "Ana Souza",
        email: "ana.souza@email.com",
        whatsapp: "16999990004",
    },
    {
        cpf_cnpj: "55555555555",
        nome: "Carlos Pereira",
        email: "carlos.pereira@email.com",
        whatsapp: "16999990005",
    },
    {
        cpf_cnpj: "66666666666",
        nome: "Fernanda Lima",
        email: "fernanda.lima@email.com",
        whatsapp: "16999990006",
    },
    {
        cpf_cnpj: "77777777777",
        nome: "Lucas Almeida",
        email: "lucas.almeida@email.com",
        whatsapp: "16999990007",
    },
    {
        cpf_cnpj: "88888888888",
        nome: "Juliana Costa",
        email: "juliana.costa@email.com",
        whatsapp: "16999990008",
    },
    {
        cpf_cnpj: "99999999999",
        nome: "Ricardo Gomes",
        email: "ricardo.gomes@email.com",
        whatsapp: "16999990009",
    },
    {
        cpf_cnpj: "10101010101",
        nome: "Patrícia Rocha",
        email: "patricia.rocha@email.com",
        whatsapp: "16999990010",
    },
    {
        cpf_cnpj: "12121212121",
        nome: "Marcos Ferreira",
        email: "marcos.ferreira@email.com",
        whatsapp: "16999990011",
    },
    {
        cpf_cnpj: "13131313131",
        nome: "Camila Martins",
        email: "camila.martins@email.com",
        whatsapp: "16999990012",
    },
];

export const testeTransacoes: TransacaoInterface[] = [
    {
        id: "trx-001",
        id_comprador: "11111111111",
        id_ingresso: 1,
        metodo_pagamento: "pix",
        id_pagamento_mp: "mp-001",
        status_pagamento: "aprovado",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-01T10:00:00Z",
    },
    {
        id: "trx-002",
        id_comprador: "22222222222",
        id_ingresso: 0,
        metodo_pagamento: "cartao",
        id_pagamento_mp: "mp-002",
        status_pagamento: "aprovado",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-01T11:00:00Z",
    },
    {
        id: "trx-003",
        id_comprador: "33333333333",
        metodo_pagamento: "pix",
        id_ingresso: 1,
        id_pagamento_mp: "mp-003",
        status_pagamento: "aprovado",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-02T08:00:00Z",
    },
    {
        id: "trx-004",
        id_comprador: "44444444444",
        id_ingresso: 0,
        metodo_pagamento: "cartao",
        id_pagamento_mp: "mp-004",
        status_pagamento: "aprovado",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-02T09:00:00Z",
    },
    {
        id: "trx-005",
        id_comprador: "55555555555",
        id_ingresso: 1,
        metodo_pagamento: "pix",
        id_pagamento_mp: "mp-005",
        status_pagamento: "aprovado",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-03T10:00:00Z",
    },
    {
        id: "trx-006",
        id_comprador: "66666666666",
        id_ingresso: 0,
        metodo_pagamento: "cartao",
        id_pagamento_mp: "mp-006",
        status_pagamento: "aprovado",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-04T10:00:00Z",
    },
    {
        id: "trx-007",
        id_comprador: "77777777777",
        id_ingresso: 1,
        id_pagamento_mp: "mp-007",
        status_pagamento: "aprovado",
        valor_pedido: 100,
        metodo_pagamento: "pix",
        data_hora_pedido: "2026-05-05T10:00:00Z",
    },
    {
        id: "trx-008",
        id_comprador: "88888888888",
        id_ingresso: 0,
        id_pagamento_mp: "mp-008",
        metodo_pagamento: "cartao",
        status_pagamento: "aprovado",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-06T10:00:00Z",
    },
    {
        id: "trx-009",
        id_comprador: "99999999999",
        id_ingresso: 1,
        id_pagamento_mp: "mp-009",
        status_pagamento: "aprovado",
        metodo_pagamento: "pix",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-07T10:00:00Z",
    },
    {
        id: "trx-010",
        id_comprador: "10101010101",
        id_ingresso: 0,
        id_pagamento_mp: "mp-010",
        status_pagamento: "aprovado",
        valor_pedido: 60,
        metodo_pagamento: "cartao",
        data_hora_pedido: "2026-05-08T10:00:00Z",
    },
    {
        id: "trx-011",
        id_comprador: "12121212121",
        id_ingresso: 1,
        id_pagamento_mp: "mp-011",
        status_pagamento: "aprovado",
        metodo_pagamento: "pix",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-09T10:00:00Z",
    },
    {
        id: "trx-012",
        id_comprador: "13131313131",
        id_ingresso: 0,
        id_pagamento_mp: "mp-012",
        status_pagamento: "aprovado",
        metodo_pagamento: "cartao",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-10T10:00:00Z",
    },
    {
        id: "trx-013",
        id_comprador: "11111111111",
        id_ingresso: 1,
        id_pagamento_mp: "mp-013",
        status_pagamento: "aprovado",
        metodo_pagamento: "pix",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-11T10:00:00Z",
    },
    {
        id: "trx-014",
        id_comprador: "22222222222",
        id_ingresso: 0,
        id_pagamento_mp: "mp-014",
        status_pagamento: "aprovado",
        metodo_pagamento: "cartao",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-12T10:00:00Z",
    },

    {
        id: "trx-015",
        id_comprador: "33333333333",
        id_ingresso: 1,
        id_pagamento_mp: "mp-015",
        status_pagamento: "pendente",
        valor_pedido: 100,
        metodo_pagamento: "pix",
        data_hora_pedido: "2026-05-13T10:00:00Z",
    },
    {
        id: "trx-016",
        id_comprador: "44444444444",
        id_ingresso: 0,
        id_pagamento_mp: "mp-016",
        metodo_pagamento: "boleto",
        status_pagamento: "pendente",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-14T10:00:00Z",
    },
    {
        id: "trx-017",
        id_comprador: "55555555555",
        id_ingresso: 1,
        id_pagamento_mp: "mp-017",
        metodo_pagamento: "cartao",
        status_pagamento: "pendente",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-15T10:00:00Z",
    },
    {
        id: "trx-018",
        id_comprador: "66666666666",
        id_ingresso: 0,
        id_pagamento_mp: "mp-018",
        metodo_pagamento: "pix",
        status_pagamento: "pendente",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-16T10:00:00Z",
    },

    {
        id: "trx-019",
        id_comprador: "77777777777",
        id_ingresso: 1,
        id_pagamento_mp: "mp-019",
        metodo_pagamento: "cartao",
        status_pagamento: "cancelado",
        valor_pedido: 100,
        data_hora_pedido: "2026-05-17T10:00:00Z",
    },
    {
        id: "trx-020",
        id_comprador: "88888888888",
        id_ingresso: 0,
        metodo_pagamento: "boleto",
        id_pagamento_mp: "mp-020",
        status_pagamento: "cancelado",
        valor_pedido: 60,
        data_hora_pedido: "2026-05-18T10:00:00Z",
    },
];

export const testeCredenciais: CredencialInterface[] = [
    {
        id: 1,
        nome: "João Silva",
        id_transacao: "trx-001",
        id_cargo: 4,
        id_congregacao: 1,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
    {
        id: 2,
        nome: "Priscila Silva",
        id_transacao: "trx-001",
        id_cargo: 4,
        id_congregacao: 1,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: false,
    },

    // trx-002
    {
        id: 3,
        nome: "Maria Oliveira",
        id_transacao: "trx-002",
        id_cargo: 3,
        id_congregacao: 0,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    // trx-003
    {
        id: 4,
        nome: "Pedro Santos",
        id_transacao: "trx-003",
        id_cargo: 1,
        id_congregacao: 3,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
    {
        id: 5,
        nome: "Mariana Santos",
        id_transacao: "trx-003",
        id_cargo: 4,
        id_congregacao: 3,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: false,
    },

    {
        id: 6,
        nome: "Ana Souza",
        id_transacao: "trx-004",
        id_cargo: 0,
        id_congregacao: 10,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    {
        id: 7,
        nome: "Carlos Pereira",
        id_transacao: "trx-005",
        id_cargo: 2,
        id_congregacao: null,
        is_outra_congregacao: true,
        nome_outra_congregacao: "Assembleia de Deus Central",
        is_titular: true,
    },
    {
        id: 8,
        nome: "Patrícia Pereira",
        id_transacao: "trx-005",
        id_cargo: 4,
        id_congregacao: null,
        is_outra_congregacao: true,
        nome_outra_congregacao: "Assembleia de Deus Central",
        is_titular: false,
    },

    {
        id: 9,
        nome: "Fernanda Lima",
        id_transacao: "trx-006",
        id_cargo: 4,
        id_congregacao: 8,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    {
        id: 10,
        nome: "Lucas Almeida",
        id_transacao: "trx-007",
        id_cargo: 0,
        id_congregacao: 14,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
    {
        id: 11,
        nome: "Larissa Almeida",
        id_transacao: "trx-007",
        id_cargo: 4,
        id_congregacao: 14,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: false,
    },

    {
        id: 12,
        nome: "Juliana Costa",
        id_transacao: "trx-008",
        id_cargo: 3,
        id_congregacao: 22,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    {
        id: 13,
        nome: "Ricardo Gomes",
        id_transacao: "trx-009",
        id_cargo: 1,
        id_congregacao: null,
        is_outra_congregacao: true,
        nome_outra_congregacao: "Igreja Batista Esperança",
        is_titular: true,
    },
    {
        id: 14,
        nome: "Aline Gomes",
        id_transacao: "trx-009",
        id_cargo: 4,
        id_congregacao: null,
        is_outra_congregacao: true,
        nome_outra_congregacao: "Igreja Batista Esperança",
        is_titular: false,
    },

    {
        id: 15,
        nome: "Patrícia Rocha",
        id_transacao: "trx-010",
        id_cargo: 4,
        id_congregacao: 35,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    {
        id: 16,
        nome: "Marcos Ferreira",
        id_transacao: "trx-011",
        id_cargo: 2,
        id_congregacao: 24,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
    {
        id: 17,
        nome: "Daniela Ferreira",
        id_transacao: "trx-011",
        id_cargo: 4,
        id_congregacao: 24,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: false,
    },

    {
        id: 18,
        nome: "Camila Martins",
        id_transacao: "trx-012",
        id_cargo: 3,
        id_congregacao: 30,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },

    {
        id: 19,
        nome: "João Silva",
        id_transacao: "trx-013",
        id_cargo: 0,
        id_congregacao: 1,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
    {
        id: 20,
        nome: "Priscila Silva",
        id_transacao: "trx-013",
        id_cargo: 4,
        id_congregacao: 1,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: false,
    },

    {
        id: 21,
        nome: "Maria Oliveira",
        id_transacao: "trx-014",
        id_cargo: 3,
        id_congregacao: 0,
        is_outra_congregacao: false,
        nome_outra_congregacao: null,
        is_titular: true,
    },
];

export const testeCheckins = [
    {
        id: 1,
        id_credencial: 1,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-10T18:01:00Z",
    },
    {
        id: 2,
        id_credencial: 2,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-10T18:02:00Z",
    },
    {
        id: 3,
        id_credencial: 3,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-10T18:05:00Z",
    },
    {
        id: 4,
        id_credencial: 4,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-10T18:07:00Z",
    },
    {
        id: 5,
        id_credencial: 5,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-10T18:08:00Z",
    },

    {
        id: 6,
        id_credencial: 1,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-11T18:00:00Z",
    },
    {
        id: 7,
        id_credencial: 3,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-11T18:10:00Z",
    },
    {
        id: 8,
        id_credencial: 6,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-11T18:12:00Z",
    },

    {
        id: 9,
        id_credencial: 7,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-12T18:00:00Z",
    },
    {
        id: 10,
        id_credencial: 8,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-12T18:01:00Z",
    },
    {
        id: 11,
        id_credencial: 9,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-12T18:05:00Z",
    },

    {
        id: 12,
        id_credencial: 10,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:00:00Z",
    },
    {
        id: 13,
        id_credencial: 11,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:03:00Z",
    },
    {
        id: 14,
        id_credencial: 12,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:06:00Z",
    },

    {
        id: 15,
        id_credencial: 13,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:10:00Z",
    },
    {
        id: 16,
        id_credencial: 15,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:11:00Z",
    },

    {
        id: 17,
        id_credencial: 16,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:15:00Z",
    },
    {
        id: 18,
        id_credencial: 17,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:16:00Z",
    },

    {
        id: 19,
        id_credencial: 19,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:20:00Z",
    },
    {
        id: 20,
        id_credencial: 20,
        id_usuario: "uuid-1",
        data_hora_checkin: "2026-07-13T18:21:00Z",
    },
];
export const testeCheckinResponses: CheckinResponse[] = [
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 2,
                nome: "Priscila Silva",
                is_titular: false,
                cargo: "membro",
                congregacao: "sede",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "11111111111",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 0 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 3,
                nome: "Maria Oliveira",
                is_titular: true,
                cargo: "cooperador",
                congregacao: "kemel",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "22222222222",
            },
            ingresso: { nome_tipo: "individual" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 4,
                nome: "Pedro Santos",
                is_titular: true,
                cargo: "diácono",
                congregacao: "brasilândia",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "33333333333",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 5,
                nome: "Mariana Santos",
                is_titular: false,
                cargo: "membro",
                congregacao: "brasilândia",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "33333333333",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 1,
                nome: "João Silva",
                is_titular: true,
                cargo: "membro",
                congregacao: "sede",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "11111111111",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 2 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 6,
                nome: "Ana Souza",
                is_titular: true,
                cargo: "obreiro",
                congregacao: "fátima",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "44444444444",
            },
            ingresso: { nome_tipo: "individual" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 7,
                nome: "Carlos Pereira",
                is_titular: true,
                cargo: "pastor",
                congregacao: null,
                is_outra_congregacao: true,
                nome_outra_congregacao: "Assembleia de Deus Central",
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "55555555555",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 8,
                nome: "Patrícia Pereira",
                is_titular: false,
                cargo: "membro",
                congregacao: null,
                is_outra_congregacao: true,
                nome_outra_congregacao: "Assembleia de Deus Central",
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "55555555555",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 9,
                nome: "Fernanda Lima",
                is_titular: true,
                cargo: "membro",
                congregacao: "eduardo",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "66666666666",
            },
            ingresso: { nome_tipo: "individual" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 10,
                nome: "Lucas Almeida",
                is_titular: true,
                cargo: "obreiro",
                congregacao: "macedônia",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "77777777777",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 11,
                nome: "Larissa Almeida",
                is_titular: false,
                cargo: "membro",
                congregacao: "macedônia",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "77777777777",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 12,
                nome: "Juliana Costa",
                is_titular: true,
                cargo: "cooperador",
                congregacao: "tereza",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "88888888888",
            },
            ingresso: { nome_tipo: "individual" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 13,
                nome: "Ricardo Gomes",
                is_titular: true,
                cargo: "diácono",
                congregacao: null,
                is_outra_congregacao: true,
                nome_outra_congregacao: "Igreja Batista Esperança",
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "99999999999",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 15,
                nome: "Patrícia Rocha",
                is_titular: true,
                cargo: "membro",
                congregacao: "mg rio pomba",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "10101010101",
            },
            ingresso: { nome_tipo: "individual" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 16,
                nome: "Marcos Ferreira",
                is_titular: true,
                cargo: "pastor",
                congregacao: "valo verde",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "12121212121",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 17,
                nome: "Daniela Ferreira",
                is_titular: false,
                cargo: "membro",
                congregacao: "valo verde",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "12121212121",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 19,
                nome: "João Silva",
                is_titular: true,
                cargo: "obreiro",
                congregacao: "sede",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "11111111111",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
    {
        sucesso: true,
        dados: {
            credencial: {
                id: 20,
                nome: "Priscila Silva",
                is_titular: false,
                cargo: "membro",
                congregacao: "sede",
                is_outra_congregacao: false,
                nome_outra_congregacao: null,
            },
            transacao: {
                status_pagamento: "aprovado",
                cpf_comprador: "11111111111",
            },
            ingresso: { nome_tipo: "casal" },
            checkin_hoje: { quantidade_registros: 1 },
        },
    },
];
